### PR TITLE
refactor: add draw by timeout/disconnect/stall/illegal move

### PR DESCRIPTION
**Pull request by gahtan-syarif**
make fc consistent with fide and uscf rules as well as with cutechess

fix https://github.com/Disservin/fastchess/issues/410

### CODE REVIEW

**Comment by gahtan-syarif** [comment]
```
+ grep 'Finished game'
+ sort -n -k 3
+ diff ./cutechess-cli-out.finished ./fastchess-out.finished
35c35
< Finished game 35 (sf_1 vs sf_2): 1/2-1/2 {Draw by adjudication}
---
> Finished game 35 (sf_1 vs sf_2): 1/2-1/2 {Draw by insufficient mating material}
```
how do i access the pgn for this?

**Comment by gahtan-syarif** [comment]
done 👍

**Comment by gahtan-syarif** [comment]
Btw finding all the situations in which only one side has no legal set of moves for checkmate is quite complex, so i decided to take the cutechess route of doing it by adjudicating as draws when the opponent only has a lone king: https://github.com/cutechess/cutechess/pull/717

**Comment by Disservin** [comment]
mh does cutechess have the same termination strings? i find this weird tbh, maybe it should be behind a "strict fide" feature but i don't care too much about that as of now because it's not the main focus

**Comment by gahtan-syarif** [comment]
Yeah cutechess has the same termination strings

**Comment by Disservin** [comment]
mh.. i don't really like this, this primarily to test engines, we don't need 100% fide compliance, if so the first illegal move should be ignored and the engine asked to make another move and only lose on the second move. Making the engine lose in 100% of the cases is more consistent imo

**Pull request closed without merging**
