### PR TITLE
fix: missing newline

### PR DESCRIPTION
**Pull request by gahtan-syarif**

### CODE REVIEW

**Comment by Disservin** [comment]
? https://github.com/Disservin/fastchess/blob/e076542f9bc42a245fb8c2d3268269641d6ba7ea/app/src/matchmaking/output/output_fastchess.hpp#L67C48-L67C51

**Comment by Disservin** [comment]
```
--------------------------------------------------
Results of cdb1 vs cdb2 (5+0.01, 1t, 16MB, UHO_Lichess_4852_v1.epd):
Elo: -34.86 +/- 119.77, nElo: -65.66 +/- 215.34
LOS: 27.50 %, DrawRatio: 40.00 %, PairsRatio: 0.50
Games: 10, Wins: 2, Losses: 3, Draws: 5, Points: 4.5 (45.00 %)
Ptnml(0-2): [0, 2, 2, 1, 0], WL/DD Ratio: 1.00LLR: -0.05 (-2.94, 2.94) [0.00, 10.00]

--------------------------------------------------
```

**Comment by gahtan-syarif** [comment]
> ? https://github.com/Disservin/fastchess/blob/e076542f9bc42a245fb8c2d3268269641d6ba7ea/app/src/matchmaking/output/output_fastchess.hpp#L67C48-L67C51

thats weird, in the e2e test it looks like this
```
--------------------------------------------------
Results of random_move_1 vs random_move_2 (2+0.02, NULL, 16MB, openings.epd):
Elo: -0.00 +/- 0.00, nElo: nan +/- nan
LOS: nan %, DrawRatio: 100.00 %, PairsRatio: nan
Games: 10, Wins: 0, Losses: 0, Draws: 10, Points: 5.0 (50.00 %)
Ptnml(0-2): [0, 0, 5, 0, 0], WL/DD Ratio: 0.00--------------------------------------------------
```

**Comment by Disservin** [comment]
https://github.com/Disservin/fastchess/commit/5d80edd4722b587d56413416e55076c9a829cfe0

**Pull request closed without merging**
