### PR TITLE
Wip Multiple Engines

### PR DESCRIPTION
**Pull request by Disservin**

### CODE REVIEW

**Comment by gahtan-syarif** [comment]
For the elo rating for multiple engines what cutechess does is it sums up the total win-draw-loss of each engine and calculate the elo from there. In fastchess the same can be done but this time by summing up the pentanomials

**Comment by Disservin** [comment]
> For the elo rating for multiple engines what cutechess does is it sums up the total win-draw-loss of each engine and calculate the elo from there. In fastchess the same can be done but this time by summing up the pentanomials

the current state should already have this

**Comment by Disservin** [comment]
This is the current output
```
Rank Name                             Elo        +/-       nElo        +/-      Games      Score       Draw
   1 engine1                        46.60      39.76     148.15     124.33         30      56.7%      73.3%
   2 engine3                        23.20      44.30      65.66     124.33         30      53.3%      73.3%
   3 engine4                       -23.20      44.30     -65.66     124.33         30      46.7%      73.3%
   4 engine2                       -46.60      39.76    -148.15     124.33         30      43.3%      73.3%
```

**Comment by Disservin** [comment]
anything else which needs to be changed?

**Comment by gahtan-syarif** [comment]
Perhaps display the summed pentanomials in the ratings output?

**Comment by Disservin** [comment]
```
Rank Name                             Elo        +/-       nElo        +/-      Games      Score       Draw           Ptnml(0-2)
   1 engine4                        23.20      55.06      52.98     124.33         30      53.3%      60.0%      [0, 2, 9, 4, 0]
   2 engine2                        -0.00      56.08       0.00     124.33         30      50.0%      60.0%      [0, 3, 9, 3, 0]
   3 engine1                       -11.59      39.08     -37.04     124.33         30      48.3%      80.0%     [0, 2, 12, 1, 0]
   4 engine3                       -11.59      39.08     -37.04     124.33         30      48.3%      80.0%     [0, 2, 12, 1, 0]
```

**Comment by gahtan-syarif** [comment]
I just noticed nelo error bars always stay the same as long as the number of games is the same, pretty cool

**Pull request merged**
