### PR TITLE
feat: add option to only log stderr

### PR DESCRIPTION
**Pull request by gahtan-syarif**
this acts as replacement of cutechess `stderr=arg`

### CODE REVIEW

**Comment by Disservin** [comment]
Mh tbh I dont think this is really meaningful, you will only get the stderr of the engine which is likely not much and no clear idea how to reproduce.
Also stderr is currently not tracked on windows.

**Comment by gahtan-syarif** [comment]
The goal is mostly as a replacement to cutechess 'stderr=arg',  i think theres some value in it as regular log files can get insanely big on long tests and sometimes you just want to see if something can run without any errors

**Comment by Disservin** [comment]
well but the usage is different, stderr got added because cutechess completely lacked that functionality and one couldnt see the stderr of the engines and the way they have it implemented right now was just the easiest route https://github.com/cutechess/cutechess/issues/8

**Comment by Disservin** [comment]
i could imagine a reduced log, which only prints engine outputs

**Comment by Disservin** [comment]
ill close this until then

**Pull request closed without merging**
