### PR TITLE
refactor: use packedformat for the epd book

### PR DESCRIPTION
**Pull request by Disservin**

### CODE REVIEW

**Comment by Disservin** [comment]
removed the
```
    truncate(rounds_);
    shrink();
```
calls and measured over valgrind-massfiv, peak memory consumption went from 350MB down to 150MB for the `UHO_Lichess_4852_v1.epd` book

**Comment by Disservin** [comment]
needs a wrapper for the move counters, and needs to pass chess960 if it is chess960 to the encoding and the pgn book should also use this

**Comment by gahtan-syarif** [comment]
it might be worth adding a unit test for this for cases where:
1. pure fens ( no `;` )
2. epds with hmvc and fmvn movecounters
3. epds with only hmvc/only fmvn counters
4. epds with no movecounters

**Comment by Disservin** [comment]
> 1. pure fens ( no `;` )

no `;` ?

**Pull request closed without merging**
